### PR TITLE
Added fixes for nested cues and new lineBreak property

### PR DESCRIPTION
**Pull request by predikament**
Fixed:
- Styled nested cues are now displayed on one line where intended
- Spacing between nested cues fixed by using `<br>` in place of `<span>` / `<div>`

### CODE REVIEW

**Comment by enrico-bardelli** [comment]
it would be a good idea to have a pr only with code changes, to make it easy to cherry pick and merge with future updates of the player

**Comment by predikament** [comment]
> 
> 
> it would be a good idea to have a pr only with code changes, to make it easy to cherry pick and merge with future updates of the player

Sure, but we are diverging quite far from Shaka now in terms of what's in their master branch, so I think next time we need to do a full sweep and grab all of their changes anyway.

I can make another PR, but this process takes like 30 minutes to get done with the building and all. Or do you mean to do the build after we've merged the changes?

**Comment by asgvard** [comment]
According to what we have discussed, the PR should contain only the source code changes: https://github.com/Norigin/frontend-guidelines/blob/master/ShakaFork.md
Then the Jenkins should make the /dist build after the PR is merged

**Comment by predikament** [comment]
> 
> 
> According to what we have discussed, the PR should contain only the source code changes: https://github.com/Norigin/frontend-guidelines/blob/master/ShakaFork.md
> Then the Jenkins should make the /dist build after the PR is merged

Alright, but then this process is a bit cumbersome:
- Do changes
- Make sure it builds
- Revert build
- Make PR with code changes
- Make build
- Make release

Yes? 😅 Anyway, I am fixing it now. Thanks.

**Comment by asgvard** [comment]
Yes, this is what we have discussed about the maintaining of this fork and everyone agreed to do it like this. Please feel free to propose a better way :) Otherwise if you would need to cherry pick any of the changes, it won't be possible since you would get conflicts in the /dist files and it would be hard to simply compare "our" branch with the original branch 🤷‍♂️

**Comment by predikament** [comment]
> Yes, this is what we have discussed about the maintaining of this fork and everyone agreed to do it like this. Please feel free to propose a better way :) Otherwise if you would need to cherry pick any of the changes, it won't be possible since you would get conflicts in the /dist files and it would be hard to simply compare "our" branch with the original branch 🤷‍♂️

Yup. Thanks.

**Comment by predikament** [comment]
Removed build. Ready for review, unless there's anything else that I might have done wrong.

**Review by asgvard — APPROVED** [review]
👍 
Although it's a lot of changes and I'm not sure I haven't missed anything

**Comment by asgvard** [comment]
I personally not a big fan of this process either, but it's just what we agreed to do and documented it like that, and I'm not sure how to simplify it without losing the transparency of the source code changes (PRs) 🤷

**Comment by predikament** [comment]
> I personally not a big fan of this process either, but it's just what we agreed to do and documented it like that, and I'm not sure how to simplify it without losing the transparency of the source code changes (PRs) 🤷

Yea, I know what you mean. IMO it's a bit of a shame we need to have a fork of Shaka just for the minuscule changes we have, but here we are, so I'll stick with the process we've agreed on.

Thanks!

**Pull request merged**
